import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-50 min-h-screen flex flex-col`}
      >
        <nav className="bg-white shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16">
              <div className="flex items-center">
                <Link  href="/" className="flex-shrink-0 flex items-center">
                  <span className="text-primary font-bold text-2xl">DiscoderJobs</span>
                </Link>
              </div>
              <div className="flex items-center md:hidden">
                <button type="button" className="p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100"
                  aria-expanded="false">
                  <span className="sr-only">Open main menu</span>
                  <svg className="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" aria-hidden="true">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
              <div className="hidden md:flex md:items-center md:space-x-4">
                <Link href="/" className="px-3 py-2 text-gray-700 hover:text-primary">Home</Link>
                <Link href="/jobs" className="px-3 py-2 text-gray-700 hover:text-primary">Find Jobs</Link>
                <Link href="/post-job" className="px-3 py-2 text-gray-700 hover:text-primary">Post a Job</Link>
                <Link href="/login" className="px-3 py-2 text-gray-700 hover:text-primary">Login</Link>
                <Link href="/register" className="px-3 py-2 text-gray-700 hover:text-primary">Register</Link>
                <Link href="/dashboard"
                  className="ml-4 px-4 py-2 bg-primary text-white rounded-md hover:bg-primary-dark">Dashboard</Link>
              </div>
            </div>
          </div>
          <div className="hidden md:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1">
              <Link href="/" className="block px-3 py-2 text-gray-700 hover:text-primary">Home</Link>
              <Link href="/jobs" className="block px-3 py-2 text-gray-700 hover:text-primary">Find Jobs</Link>
              <Link href="/post-job" className="block px-3 py-2 text-gray-700 hover:text-primary">Post a Job</Link>
              <Link href="/login" className="block px-3 py-2 text-gray-700 hover:text-primary">Login</Link>
              <Link href="/register" className="block px-3 py-2 text-gray-700 hover:text-primary">Register</Link>
              <Link href="/dashboard"
                className="block px-3 py-2 bg-primary text-white rounded-md hover:bg-primary-dark">Dashboard</Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
